### ISSUE TITLE
 The coordinates of the waypoint differ in the result

### ISSUE THREAD

**Issue by rimaregiani** [muyangye/Travelnetics#1]
hi! Why do the coordinates differ between the point of longitude and latitude printed when clicking a location with autocomplete and the coordinates of the waypoint printed in JavaScript?  Can you please explain it.. thankyou

![image](https://github.com/muyangye/Traveling_Salesman_Solver_Google_Maps/assets/33814014/c2e6ddd0-e0b8-4763-bf06-073141f777bf)

![image](https://github.com/muyangye/Traveling_Salesman_Solver_Google_Maps/assets/33814014/08f77e61-902b-4110-a668-cfb0e940689e)

**Comment by muyangye** [comment]
Hi @rimaregiani, this is because in order to calculate the distance between 2 waypoints using [Haversine Distance](https://en.wikipedia.org/wiki/Haversine_formula), we need to convert latitude and longitude to radians on line 144 and 155 of `index.html`. The magic number 0.0174533 is approximately π/180.  If you put the `console.log` before the conversion (and before `console.clear()` on line 140), I believe you will see the same console log as the webpage. Please let me know if the issue persists🙂!

**Comment by muyangye** [comment]
Closing this issue since it's been a week... Feel free to reopen!
